export const siteConfig = {
  businessName: 'Geli Construction Services',
  phoneDisplay: '0494 802 784',
  phoneHref: 'tel:+61494802784',
  emailDisplay: 'g.lconstructionservices82@gmail.com',
  emailHref: 'mailto:g.lconstructionservices82@gmail.com',
  abn: '65 522 741 328',
  domain: 'https://geliconstructionservices.com.au',
  serviceArea: 'South-East Melbourne, Dandenong Ranges, Gippsland, Bass Coast, South Gippsland & Latrobe Valley',
  tagline: 'Concreting and outdoor construction for homes and outdoor spaces.',
  description:
    'Concreting, stonework, excavation, retaining walls, irrigation, drainage and outdoor finishing across South-East Melbourne, Gippsland and surrounding areas.',
  nav: [
    { label: 'Home', href: '/' },
    { label: 'Services', href: '/services/' },
    { label: 'Projects', href: '/projects/' },
    { label: 'About', href: '/about/' },
    { label: 'Contact', href: '/contact/' },
  ],
  services: [
    {
      name: 'Concreting',
      shortName: 'Concreting',
      slug: 'concreting',
      heading: 'Concrete built around your property.',
      summary: 'Concrete for driveways, footpaths, alfresco areas and steps, with finish options to suit the project.',
      pageSummary: 'Concrete for driveways, footpaths, alfresco areas and steps, with a range of finishes available depending on the project.',
      examples: ['Driveways', 'Footpaths', 'Alfresco areas', 'Steps', 'Plain concrete', 'Coloured concrete', 'Exposed aggregate'],
      cta: 'Request a concreting quote',
      filter: 'Concreting',
      icon: 'layers',
    },
    {
      name: 'Excavation',
      shortName: 'Excavation',
      slug: 'excavation',
      heading: 'Ground preparation for the work ahead.',
      summary: 'Excavation and ground preparation for concrete and outdoor construction work.',
      pageSummary: 'Excavation and ground preparation for concrete and other outdoor construction work.',
      examples: ['Excavation', 'Ground preparation for concrete', 'Preparation for outdoor works'],
      cta: 'Request an excavation quote',
      filter: 'Excavation',
      icon: 'shovel',
    },
    {
      name: 'Stonework & Outdoor Tiling',
      shortName: 'Stonework & Outdoor Tiling',
      slug: 'stonework-outdoor-tiling',
      heading: 'Stone and tile for outdoor spaces.',
      summary: 'Natural stone and outdoor tile installation for paths, entertaining areas and external finishes.',
      pageSummary: 'Natural stone and outdoor tile installation for paths, entertaining areas and external finishes.',
      examples: ['Bluestone paving', 'Outdoor tiling', 'Natural stone paving', 'Stone paving & tiling', 'Outdoor stone & tile installation'],
      cta: 'Request a stonework quote',
      filter: 'Stonework & Outdoor Tiling',
      icon: 'panels-top-left',
    },
    {
      name: 'Outdoor Finishing & Landscaping',
      shortName: 'Outdoor Finishing',
      slug: 'outdoor-finishing',
      heading: 'The details that complete the space.',
      summary: 'Finishing elements that help complete and improve outdoor areas.',
      pageSummary: 'Outdoor finishing elements for creating practical and finished areas around the property.',
      examples: ['Outdoor decorative elements', 'Outdoor lighting', 'Rocks', 'Grass', 'Mulch', 'Gravel', 'Pebbles', 'Plants'],
      cta: 'Discuss your outdoor project',
      filter: 'Outdoor Finishing & Landscaping',
      icon: 'sprout',
    },
    {
      name: 'Irrigation & Drainage',
      shortName: 'Irrigation & Drainage',
      slug: 'irrigation-drainage',
      heading: 'Water where it belongs.',
      summary: 'Irrigation and drainage solutions for outdoor areas.',
      pageSummary: 'Irrigation and drainage solutions for outdoor areas.',
      examples: ['Water irrigation systems', 'Drainage'],
      cta: 'Request a quote',
      filter: 'Irrigation & Drainage',
      icon: 'waves',
    },
    {
      name: 'Retaining Walls',
      shortName: 'Retaining Walls',
      slug: 'retaining-walls',
      heading: 'Practical retaining solutions.',
      summary: 'Retaining wall construction for outdoor areas and landscape levels.',
      pageSummary: 'Retaining wall construction for outdoor spaces and changing landscape levels.',
      examples: ['Retaining walls'],
      cta: 'Request a retaining wall quote',
      filter: 'Retaining Walls',
      icon: 'brick-wall',
    },
  ],
} as const;

export type Service = (typeof siteConfig.services)[number];
